baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'suimu的个人空间'
theme = "m10c"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[[params.social]]
  icon = "github"
  name = "GitHub"
  url = "https://github.com/shuimu0579"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"
