

baseURL = 'https://suimulearn.cn/'
name = "suimu"
title = 'suimu的空间'
paginate = 8
theme = "m10c"

languageCode = 'zh-CN'
enableEmoji = true
date_format = "2006-01-02"
time_format = "3:04 PM"
lightgallery = true


[author]
  name = "suimu"
  homepage = "https://suimulearn.cn/"
  mail = "shuimu0579@gmail.com"

[params]
  avatar = "/avatar.jpeg" 
  favicon = "https://s2.loli.net/2022/08/02/Pq5vFfjpWy1LKnd.png"
  description = "莫道昆明池水浅，观鱼胜过富春江"
  wechat = "https://s2.loli.net/2022/07/31/svrIXDtGHNleLgO.jpg"
  enableGoogleAnalytics = true
  enableBaiduAnalytics = false
  googleAnalytics = "UA-123-45"
  [params.style]
    darkestColor = "#083537"
    darkColor = "#212121"
    lightColor = "#f5e3e0"
    lightestColor = "#f5f5f5"
    primaryColor = "#ffffff"
  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/shuimu0579"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/shuimu19"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
